package ewm.location.repository;

import ewm.location.model.*;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import java.util.Optional;

public interface LocationRepository extends
        JpaRepository<Location, Long>,
        JpaSpecificationExecutor<Location> {

    // Поиск существующей локации с таким же именем в пределах указанного радиуса
    @Query(value = """
        SELECT * FROM locations l
        WHERE l.name = :name
            AND calc_dist(:lat, :lon, l.latitude, l.longitude) <= :radius
        LIMIT 1
        """, nativeQuery = true)
    Optional<Location> findDuplicates(
            @Param("name") String name,
            @Param("lat") double lat,
            @Param("lon") double lon,
            @Param("radius") double radius
    );

    // Поиск ближайшей автосгенерированной локации в пределах радиуса 20 м.
    @Query(value = """
        SELECT * FROM locations l
        WHERE l.state = 'AUTO_GENERATED'
            AND calc_dist(:latitude, :longitude, l.latitude, l.longitude) <= 20
        LIMIT 1
        """, nativeQuery = true)
    Optional<Location> findNearByAutoGenerated(Double latitude, Double longitude);

    // Поиск локации по id и состоянию
    Optional<Location> findByIdAndState(Long id, LocationState state);
}
